version: "3.9"

services:
  db:
    image: postgres:13.3
    restart: unless-stopped
    environment:
      - POSTGRES_DB=segments
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data/
      - ./assets/postgres/init.sql:/docker-entrypoint-initdb.d/1-shema.sql
  app:
    build: .
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - ./config:/app/config
    environment:
      - CONFIG_PATH=/app/config/local.yaml

volumes:
  db: